resolver: lts-2.22

extra-deps:
  - fsnotify-0.2.1
  - hfsevents-0.1.6
  - managed-1.0.5
  - mtl-2.2.1
  - streaming-0.1.4.3
  - transformers-0.4.3.0
  - transformers-compat-0.4.0.3

flags:
  transformers-compat:
    two: false
    three: false
