name: steeloverseer
version: 2.1.0.1
license: BSD3
license-file: LICENSE
maintainer: peterbecich@gmail.com
stability: stable
github: schell/steeloverseer
synopsis: A file watcher and development tool.
description: >
    A command line tool that responds to filesystem events.
    Allows the user to automatically execute commands after
    files are added or updated. Watches files using regular
    expressions.
category: Development
author:
  - Schell Scivally
  - Mitchell Rosen
extra-source-files:
  - README.md

ghc-options: -Wall

build-tool-depends:
  hspec-discover

tested-with:
  - GHC==9.2.2

default-extensions:
  - BangPatterns
  - DeriveDataTypeable
  - DeriveFunctor
  - FlexibleContexts
  - InstanceSigs
  - LambdaCase
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables
  - ViewPatterns

dependencies:
  - async >= 2.0
  - base >= 4.0 && < 5.0
  - bytestring >= 0.10
  - exceptions
  - fsnotify >= 0.3 && < 0.4
  - managed >= 1.0.1
  - regex-tdfa >= 1.2
  - stm >= 2.4
  - streaming >= 0.1.0 && < 0.3
  - text >= 1.2
  - yaml >= 0.8

library:
  source-dirs: src
  dependencies:
    - aeson         >= 0.8
    - ansi-terminal >= 0.6.2
    - process       >= 1.6 && < 1.7
    - unix
  other-modules: []

executables:
  sos:
    main: Main.hs
    source-dirs: app
    dependencies:
      - steeloverseer
      - directory >= 1.2
      - filepath >= 1.3
      - optparse-applicative >= 0.11
    other-modules: []
    ghc-options: -threaded

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - steeloverseer
      - hspec
